#!/bin/bash

APP=`dirname $0`
SCRIPT="$APP/index.js"
PID="/var/run/json-server.pid"
LOG="$APP/log"

forever -p $APP --pidFile $PID -e $LOG/error.log -l $LOG/access.log -o $LOG/output.log -a -d $SCRIPT
